[project]
name = "youtube-university"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ollama>=0.6.3",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
]

[project.scripts]
youtube-university = "youtube_university:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
