# src/youtube_university/llm.py
"""Generate a structured learning curriculum using the local Ollama model."""
import ollama
from pydantic import BaseModel, ValidationError

MODEL = "llama3.2:3b"

# LLM INSTRUCTIONS  ___________________________________________________________________________
# Defines the model's role and builds instructions from the learner's input.
SYSTEM_PROMPT = (
    "You are a curriculum designer for self-taught learners who study with free YouTube videos. "
    "Respond only with JSON matching the requested structure. "
    "Never invent video titles, channels, or URLs; only propose search queries."
)


def build_prompt(profile: dict) -> str:
    """Build the LLM prompt using the learner's topic, level, goal, and study time."""
    return f"""Create a curriculum for the profile described below.

LEARNER'S PROFILE
- Topic: {profile['topic']}
- Level: {profile['level']}
- Goal: {profile['goal']}
- Hours Per Week: {profile['hours_per_week']}

REQUIREMENTS
- Create exactly 4 modules.
- Each module should progress (build) off the previous one.
- Each module should represent about one week of study.
- Each module must have a short title.
- Each module should have 2 to 3 objectives starting with an action verb.
- Each module must have exactly 2 search queries.
- Each search query must be between 3 to 8 words.
- Each search query should be suitable for a YouTube search.
- Search queries may not have channel names.
- Stay focused on the learner's goal. Do not add topics beyond the goal.

FIELDS
- Curriculum title: A short name for the complete learning plan.
- modules: The four ordered stages of the curriculum.
- Module title: A short name describing that module's topic.
- objectives: Specific things the learner should be able to do after the module.
- search_queries: Phrases used to search YouTube for videos teaching that module.

"""



# LLM OUTPUT STRUCTURE ________________________________________________________________________
# Defines the structured curriculum that the LLM must return.
class Module(BaseModel):
    """One module within the generated curriculum."""
    title: str
    objectives: list[str]
    search_queries: list[str]


class Curriculum(BaseModel):
    """The complete learning curriculum generated by the LLM."""
    title: str
    modules: list[Module]



# CURRICULUM GENERATION _______________________________________________________________________
def generate_curriculum(profile: dict) -> Curriculum:
    """One LLM call: learner profile in, validated Curriculum out."""
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": build_prompt(profile)},
    ]
    
    for attempt in range(2):                         # first try + one retry
        try:
            response = ollama.chat(
                model=MODEL,
                messages=messages,
                format=Curriculum.model_json_schema(),   # constrains the output to this JSON shape
                options={"temperature": 0.2},            # low = more consistent
            )
        except ConnectionError:
            raise RuntimeError("Cannot reach Ollama. Is it running?") from None
        except ollama.ResponseError as err:
            raise RuntimeError(f"Ollama error: {err.error}") from None

        text = response.message.content
        
        try:
            return Curriculum.model_validate_json(text)                  # a STRING containing JSON, not an object yet
        except ValidationError:
            print("The model's answer didn't match the format. Retrying...")
    raise RuntimeError("The model did not return a usable curriculum after 2 attempts.")